# run.py

import pytest
import argparse
import os
import sys
from dotenv import load_dotenv
from core.logger_config import logger

# =================================================================
# 1. Global Configuration Loading
# =================================================================
# Load the unique .env file from project root directory on framework startup.
logger.info("Loading framework database configuration from .env file")
load_dotenv()

# Define a hardcoded default environment
DEFAULT_ENV = 'dev'

# =================================================================
# 2. Main Execution Function
# =================================================================

def main():
    """
    Main entry point for the framework.
    Responsible for parsing command line arguments, determining runtime environment
    and parallelization settings, then launching pytest.
    """
    # 1. Get default values from system environment variables
    env_from_os = os.getenv('TEST_ENV')
    parallel_from_os = os.getenv('PYTEST_PARALLEL_WORKERS')

    parser = argparse.ArgumentParser(
        description="API Test Runner - A highly configurable, data-driven framework.",
        formatter_class=argparse.RawTextHelpFormatter
    )

    # 2. Define all command line arguments
    parser.add_argument(
        "--env",
        type=str,
        default=None,
        help=f"Specify test target environment (e.g., dev, uat).\n"
             f"Priority: Command-line > Environment Variable TEST_ENV > Default '{DEFAULT_ENV}'."
    )

    parser.add_argument(
        "-n", "--parallel",
        type=str,
        default=parallel_from_os,
        help=f"Number of parallel processes (e.g., 4, 8, or 'auto').\n"
             f"Priority: Command-line > Environment Variable PYTEST_PARALLEL_WORKERS (Current: {parallel_from_os})."
    )

    parser.add_argument("--service", type=str, help="Filter by service")
    parser.add_argument("--module", type=str, help="Filter by module")
    parser.add_argument("--component", type=str, help="Filter by component")
    parser.add_argument("--tags", type=str, help="Filter by tags, comma-separated (e.g., P0,smoke)")
    parser.add_argument("--jira", type=str, help="Filter by Jira ID")
    parser.add_argument("--id", type=int, help="Execute all data sets for a specific case_id")

    parser.add_argument("--debug-mode", action="store_true", help="Enable debug mode to write detailed audit logs to database")
    parser.add_argument("--run-id", type=str, help="Unique run ID generated by TaaS service (typically used internally by API service)")

    args = parser.parse_args()

    # 3. Determine final configuration based on priority strategy
    final_env = args.env or env_from_os or DEFAULT_ENV
    final_parallel = args.parallel or parallel_from_os

    logger.info(f"Final environment for this run: {final_env}")
    logger.info(f"Source: {'Command-line' if args.env else ('Environment Variable' if env_from_os else 'Hardcoded Default')}")
    if final_parallel:
        logger.info(f"Parallel execution enabled with {final_parallel} workers")

    # 4. Prepare pytest argument list
    report_dir = 'reports/allure-results'
    pytest_args = ['tests/test_main.py', '-v', '--alluredir', report_dir]

    # Pass all parsed arguments correctly to pytest
    pytest_args.append(f"--env={final_env}")
    if final_parallel: pytest_args.extend(["-n", final_parallel])
    if args.service: pytest_args.append(f"--service={args.service}")
    if args.module: pytest_args.append(f"--module={args.module}")
    if args.component: pytest_args.append(f"--component={args.component}")
    if args.tags: pytest_args.append(f"--tags={args.tags}")
    if args.jira: pytest_args.append(f"--jira={args.jira}")
    if args.id: pytest_args.append(f"--id={args.id}")

    if args.debug_mode: pytest_args.append("--debug-mode")
    if args.run_id: pytest_args.append(f"--run-id={args.run_id}")

    # 5. Run pytest and generate reports
    if os.path.exists(report_dir):
        import shutil
        shutil.rmtree(report_dir)

    exit_code = pytest.main(pytest_args)

    logger.info("Test execution completed. Generating Allure report...")
    os.system(f'allure generate {report_dir} -o reports/allure-report --clean')

    sys.exit(exit_code)

if __name__ == '__main__':
    main()
